Parameters:
    KeyName:
        Description: The EC2 key pair to all access
        Type: AWS::EC2::KeyPair::KeyName
    GitHubOwner:
      Type: String
    GitHubRepo:
      Type: String
    GitHubBranch:
      Type: String
Resources:
    EC2InstanceLab:
        Type: AWS::EC2::Instance
        Properties:
            SecurityGroups:
                - !Ref InstanceSecurityGroup
            KeyName: !Ref KeyName
            ImageId: ami-096fda3c22c1c990a
            InstanceType: t2.micro
            IamInstanceProfile: !Ref InstanceProfile
            UserData:
              Fn::Base64:
                !Sub |
                  #!/bin/bash
                  cd tmp
                  sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
                  sudo systemctl enable amazon-ssm-agent
                  sudo systemctl start amazon-ssm-agent
    InstanceRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        ManagedPolicyArns:
          - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore'
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                - "ec2.amazonaws.com"
                - "ssm.amazonaws.com"
              Action: "sts:AssumeRole"
    InstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Roles:
          - !Ref InstanceRole
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable SSH access via port 22
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: 0.0.0.0/0
    InAssoc:
      Type: AWS::SSM::Association
      Properties:
        Name: AWS-ApplyAnsiblePlaybooks
        Targets:
          - Key: InstanceIds
            Values: [ !Ref EC2InstanceLab ]
        Parameters:
          SourceType:
            - GitHub
          SourceInfo:
            - !Sub |
                {"owner":"${GitHubOwner}",
                "repository":"${GitHubRepo}",
                "path":"/cm",
                "getOptions":"branch:${GitHubBranch}"}
          PlaybookFile:
            - apache.yml
          ExtraVariables:
            - 'SSM=True'
          Check:
            - 'False'
          Verbose:
            - '-v'
