Parameters:
    KeyName:
        Description: The EC2 key pair to all access
        Type: AWS::EC2::KeyPair::KeyName
Resources:
    EC2InstanceLab:
        Type: AWS::EC2::Instance
        Properties:
            SecurityGroups:
                - !Ref InstanceSecurityGroup
            KeyName: !Ref KeyName
            ImageId: ami-0be2609ba883822ec
            InstanceType: t2.micro
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable SSH access via port 22
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0