---

# - name: Installing Apache on Linux 
#   import_tasks: linux.yml
#   when: ansible_facts['os_family'] == 'RedHat'

- name: Install base packages
  package:
    name: ['wget','tar','unzip']
    state: present

- name: Add tomcat group
  group:
    name: tomcat

- name: Add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_source_url }}"
    dest: "{{ tomcat_install_dest }}"

- name: Create tomcat dir
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract tomcat package
  unarchive:
    src: "{{ tomcat_install_dest }}"
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    enabled: yes
    state: started

- name: Set UI access credentials
  template:
    src: tomcat-users.xml.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
  notify: restart tomcat

- name: Allow access to Tomcat Manager and Host Manager
  template:
    src: context.xml.j2
    dest: "{{ item }}"
  with_items:
    - /opt/tomcat/webapps/host-manager/META-INF/context.xml
    - /opt/tomcat/webapps/manager/META-INF/context.xml
  notify: restart tomcat
